
obj-y = mmc.o mmc_ops.o sdio.o sdio_ops.o

obj-$(CONFIG_S3C2440) += s3c24x0_mmc.o
obj-$(CONFIG_S3C6410) += s3c6410_mmc.o
obj-$(CONFIG_AT91SAM9261) += at91_mci.o

include $(TOP_DIR)/build/rules/general.mk

