obj-y = head.o exception.o

obj-$(CONFIG_IRQ_SUPPORT) += udelay.o

dir-$(CONFIG_S3C2410)     = s3c24x
dir-$(CONFIG_S3C2440)     = s3c24x
dir-$(CONFIG_S3C6410)     = s3c64x
dir-$(CONFIG_AT91SAM9261) = at91
dir-$(CONFIG_AT91SAM9263) = at91
dir-$(CONFIG_OMAP3530)    = omap3

dir-y += lib
