obj-y = head.o cpu.o cpuid.o

dir-$(CONFIG_S3C2410)     = s3c24x0
dir-$(CONFIG_S3C2440)     = s3c24x0
dir-$(CONFIG_S3C6410)     = s3c6410
dir-$(CONFIG_AT91SAM9261) = at91sam926x
dir-$(CONFIG_AT91SAM9263) = at91sam926x

PHONY += head.S
