obj-y = head.o cpu.o cpuid.o

dir-$(CONFIG_S3C2410)     = s3c24x
dir-$(CONFIG_S3C2440)     = s3c24x
dir-$(CONFIG_S3C6410)     = s3c64x
dir-$(CONFIG_AT91SAM9261) = at91
dir-$(CONFIG_AT91SAM9263) = at91
dir-$(CONFIG_OMAP3)    = omap3

PHONY += head.S
