obj-$(CONFIG_IRQ_SUPPORT) += s3c6410_irq.o s3c6410_timer.o
obj-$(CONFIG_S3C6410) += board_mw61.o
obj-$(CONFIG_UART) += s3c6410_uart.o
obj-$(CONFIG_GPU) += s3c6410_gpu.o
obj-$(CONFIG_MMC) += s3c6410_mmc.o
obj-$(CONFIG_SPI) += s3c6410_spi.o
