# UART Core Files
obj-y = uart.o

obj-$(CONFIG_UART_S3C24X) += s3c24x_uart.o
obj-$(CONFIG_UART_S3C64X) += s3c64x_uart.o
obj-$(CONFIG_UART_AT91)   += at91_uart.o
obj-$(CONFIG_UART_OMAP3)  += omap3_uart.o
