#
# Makefile for the linux YAFFS filesystem routines.
#

obj-y := yaffs_ecc.o yaffs_vfs.o yaffs_guts.o yaffs_checkptrw.o
obj-y += yaffs_packedtags1.o yaffs_packedtags2.o yaffs_nand.o
obj-y += yaffs_tagscompat.o
obj-y += yaffs_mtdif.o yaffs_mtdif1.o yaffs_mtdif2.o
obj-y += yaffs_nameval.o yaffs_attribs.o
obj-y += yaffs_allocator.o
obj-y += yaffs_yaffs1.o
obj-y += yaffs_yaffs2.o
obj-y += yaffs_bitmap.o
obj-y += yaffs_summary.o
obj-y += yaffs_verify.o
