dir-y += basic user mem go uart boot reboot
dir-$(CONFIG_FLASH) += flash
dir-$(CONFIG_NET) += ifconfig ping tftp dhclient ftp
dir-$(CONFIG_FS) += mount
dir-$(CONFIG_MMC) += disk
dir-$(CONFIG_DISPLAY) += display
