dir-y += core

obj-$(CONFIG_DM9000)    += dm9000.o
obj-$(CONFIG_CS8900)    += cs8900.o
obj-$(CONFIG_AT91_EMAC) += at91_emac.o
obj-$(CONFIG_SMSC91X)   += smsc91x.o
obj-$(CONFIG_LAN9220)   += lan9220.o
