obj-y = display_core.o video_mode.o

obj-$(CONFIG_GRAPHICS_AT91)   += at91_display.o
obj-$(CONFIG_GRAPHICS_S3C24X) += s3c24x_display.o
obj-$(CONFIG_GRAPHICS_S3C64X) += s3c64x_display.o
obj-$(CONFIG_GRAPHICS_OMAP3)  += omap3_display.o
