
obj-y = at91sam926x_gpio.o

obj-$(CONFIG_IRQ_SUPPORT) += at91sam926x_irq.o at91sam926x_timer.o
obj-$(CONFIG_AT91SAM9261) += at91sam9261_plat.o
obj-$(CONFIG_AT91SAM9263) += at91sam9263_plat.o

obj-$(CONFIG_UART) += at91sam926x_uart.o

obj-$(CONFIG_AT91SAM9261_NAND) += at91sam9261_nand.o
obj-$(CONFIG_AT91SAM9263_NAND) += at91sam9263_nand.o

obj-$(CONFIG_GPU) += at91sam9261_gpu.o

obj-$(CONFIG_MMC) += at91_mci.o
